# Generated by Django 5.0.2 on 2024-05-07 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demandes', '0005_activites_demande_bac_contrainte_unique_activite_demande_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiements_Demande_Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=50, verbose_name='Montant')),
                ('type_de_paiement', models.CharField(choices=[('En espèce', 'En espèce'), ('Via digidec lite', 'Via digidec lite')], default='En espèce', max_length=50, verbose_name='Type de paiement')),
                ('date_de_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demandes.demande_bac', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Paiement de demande BAC',
                'verbose_name_plural': 'Paiements des demandes BAC',
                'ordering': ['-date_de_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Paiements_Demande_Bepc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=50, verbose_name='Montant')),
                ('type_de_paiement', models.CharField(choices=[('En espèce', 'En espèce'), ('Via digidec lite', 'Via digidec lite')], default='En espèce', max_length=50, verbose_name='Type de paiement')),
                ('date_de_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demandes.demande_bepc', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Paiement de demande BEPC',
                'verbose_name_plural': 'Paiements des demandes BEPC',
                'ordering': ['-date_de_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Paiements_Demande_Cepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=50, verbose_name='Montant')),
                ('type_de_paiement', models.CharField(choices=[('En espèce', 'En espèce'), ('Via digidec lite', 'Via digidec lite')], default='En espèce', max_length=50, verbose_name='Type de paiement')),
                ('date_de_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demandes.demande_cepe', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Paiement de demande CEPE',
                'verbose_name_plural': 'Paiements des demandes CEPE',
                'ordering': ['-date_de_paiement'],
            },
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_bac',
            constraint=models.UniqueConstraint(fields=('demande', 'montant', 'type_de_paiement'), name='contrainte_unique_paiement_demande_bac'),
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_bepc',
            constraint=models.UniqueConstraint(fields=('demande', 'montant', 'type_de_paiement'), name='contrainte_unique_paiement_demande_bepc'),
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_cepe',
            constraint=models.UniqueConstraint(fields=('demande', 'montant', 'type_de_paiement'), name='contrainte_unique_paiement_demande_cepe'),
        ),
    ]
