# Generated by Django 5.0.2 on 2024-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0005_activites_demande_bac_contrainte_unique_activite_demande_bac_and_more'),
        ('Paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiements_demande_bac',
            name='contrainte_unique_paiement_demande_bac',
        ),
        migrations.RemoveConstraint(
            model_name='paiements_demande_bepc',
            name='contrainte_unique_paiement_demande_bepc',
        ),
        migrations.RemoveConstraint(
            model_name='paiements_demande_cepe',
            name='contrainte_unique_paiement_demande_cepe',
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_bac',
            constraint=models.UniqueConstraint(fields=('demande', 'type_de_paiement'), name='contrainte_unique_paiement_demande_bac'),
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_bepc',
            constraint=models.UniqueConstraint(fields=('demande', 'type_de_paiement'), name='contrainte_unique_paiement_demande_bepc'),
        ),
        migrations.AddConstraint(
            model_name='paiements_demande_cepe',
            constraint=models.UniqueConstraint(fields=('demande', 'type_de_paiement'), name='contrainte_unique_paiement_demande_cepe'),
        ),
    ]
