# Generated by Django 5.0.2 on 2024-05-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0005_activites_demande_bac_contrainte_unique_activite_demande_bac_and_more'),
        ('Paiements', '0003_remove_paiements_demande_bac_contrainte_unique_paiement_demande_bac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiements_demande_bac',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paiements_demande_bepc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paiements_demande_cepe',
            name='id',
        ),
        migrations.AlterField(
            model_name='paiements_demande_bac',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bac', verbose_name='Demande'),
        ),
        migrations.AlterField(
            model_name='paiements_demande_bepc',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bepc', verbose_name='Demande'),
        ),
        migrations.AlterField(
            model_name='paiements_demande_cepe',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_cepe', verbose_name='Demande'),
        ),
    ]
