# Generated by Django 5.0.2 on 2024-05-08 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demandes', '0005_activites_demande_bac_contrainte_unique_activite_demande_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registre_Demande_Bac',
            fields=[
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bac', verbose_name='Demande')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('date_de_naissance', models.CharField(max_length=50, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('domicile', models.CharField(max_length=150, verbose_name='Domicile')),
                ('numero_piece', models.CharField(max_length=150, verbose_name="Numéro de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Registre de demande BAC',
                'verbose_name_plural': 'Registre des demandes BAC',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Registre_Demande_Bepc',
            fields=[
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bac', verbose_name='Demande')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('date_de_naissance', models.CharField(max_length=50, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('domicile', models.CharField(max_length=150, verbose_name='Domicile')),
                ('numero_piece', models.CharField(max_length=150, verbose_name="Numéro de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Registre de demande BEPC',
                'verbose_name_plural': 'Registre des demandes BEPC',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Registre_Demande_Cepe',
            fields=[
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bac', verbose_name='Demande')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('date_de_naissance', models.CharField(max_length=50, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('domicile', models.CharField(max_length=150, verbose_name='Domicile')),
                ('numero_piece', models.CharField(max_length=150, verbose_name="Numéro de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Registre de demande CEPE',
                'verbose_name_plural': 'Registre des demandes CEPE',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
    ]
