# Generated by Django 5.0.2 on 2024-05-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0005_activites_demande_bac_contrainte_unique_activite_demande_bac_and_more'),
        ('Registres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registre_demande_bepc',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_bepc', verbose_name='Demande'),
        ),
        migrations.AlterField(
            model_name='registre_demande_cepe',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Demandes.demande_cepe', verbose_name='Demande'),
        ),
    ]
