# Generated by Django 5.0.2 on 2024-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande_Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('Diplome BAC', 'Diplome BAC'), ('Attestation de réussite BAC', 'Attestation de réussite BAC'), ('Relevé de notes BAC', 'Relevé de notes BAC')], default='Diplome BAC', max_length=50, verbose_name='Objet')),
                ('matricule', models.CharField(blank=True, default='Matricule non renseigné', max_length=25, null=True, verbose_name='Matricule')),
                ('nom', models.CharField(blank=True, default='Nom non renseigné', max_length=50, null=True, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, default='Prénoms non renseignés', max_length=150, null=True, verbose_name='Prénoms')),
                ('date_de_naissance', models.DateField(blank=True, default='Date de naissance non renseignée', null=True, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(blank=True, default='Lieu de naissance non renseigné', max_length=150, null=True, verbose_name='Lieu de naissance')),
                ('numero_de_telephone', models.CharField(blank=True, default='Numéro de téléphone non renseigné', max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('departement', models.CharField(blank=True, default='Département non renseigné', max_length=50, null=True, verbose_name='Département')),
                ('etablissement_d_origine', models.CharField(blank=True, default="Etablissement d'origine non renseigné", max_length=150, null=True, verbose_name="Etablissement d'origine")),
                ('annee_d_obtention_du_bac', models.CharField(blank=True, default="Année d'obtention du BAC non renseignée", max_length=4, null=True, verbose_name="Année d'obtention du BAC")),
                ('copie_couleur_de_l_acte_de_naissance', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_actes_de_naissances/', verbose_name="Copie couleur de l'acte de naissance")),
                ('copie_couleur_du_bepc', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_bepc/', verbose_name='Copie couleur du BEPC')),
                ('copie_couleur_d_une_piece_d_identite', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_pieces_d_identites/', verbose_name="Copie couleur de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Demande BAC',
                'verbose_name_plural': 'Demandes BAC',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Demande_Bepc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('Diplome BEPC', 'Diplome BEPC'), ('Attestation de réussite BEPC', 'Attestation de réussite BEPC'), ('Relevé de notes BEPC', 'Relevé de notes BEPC')], default='Diplome BEPC', max_length=50, verbose_name='Objet')),
                ('matricule', models.CharField(blank=True, default='Matricule non renseigné', max_length=25, null=True, verbose_name='Matricule')),
                ('nom', models.CharField(blank=True, default='Nom non renseigné', max_length=50, null=True, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, default='Prénoms non renseignés', max_length=150, null=True, verbose_name='Prénoms')),
                ('date_de_naissance', models.DateField(blank=True, default='Date de naissance non renseignée', null=True, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(blank=True, default='Lieu de naissance non renseigné', max_length=150, null=True, verbose_name='Lieu de naissance')),
                ('numero_de_telephone', models.CharField(blank=True, default='Numéro de téléphone non renseigné', max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('departement', models.CharField(blank=True, default='Département non renseigné', max_length=50, null=True, verbose_name='Département')),
                ('etablissement_d_origine', models.CharField(blank=True, default="Etablissement d'origine non renseigné", max_length=150, null=True, verbose_name="Etablissement d'origine")),
                ('annee_d_obtention_du_bepc', models.CharField(blank=True, default="Année d'obtention du BEPC non renseignée", max_length=4, null=True, verbose_name="Année d'obtention du BEPC")),
                ('copie_couleur_de_l_acte_de_naissance', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_actes_de_naissances/', verbose_name="Copie couleur de l'acte de naissance")),
                ('copie_couleur_du_cepe', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_cepe/', verbose_name='Copie couleur du CEPE')),
                ('copie_couleur_d_une_piece_d_identite', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_pieces_d_identites/', verbose_name="Copie couleur de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Demande BEPC',
                'verbose_name_plural': 'Demandes BEPC',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Demande_Cepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('Diplome CEPE', 'Diplome CEPE'), ('Attestation de réussite CEPE', 'Attestation de réussite CEPE'), ('Relevé de notes CEPE', 'Relevé de notes CEPE')], default='Diplome CEPE', max_length=50, verbose_name='Objet')),
                ('matricule', models.CharField(blank=True, default='Matricule non renseigné', max_length=25, null=True, verbose_name='Matricule')),
                ('nom', models.CharField(blank=True, default='Nom non renseigné', max_length=50, null=True, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, default='Prénoms non renseignés', max_length=150, null=True, verbose_name='Prénoms')),
                ('date_de_naissance', models.DateField(blank=True, default='Date de naissance non renseignée', null=True, verbose_name='Date de naissance')),
                ('lieu_de_naissance', models.CharField(blank=True, default='Lieu de naissance non renseigné', max_length=150, null=True, verbose_name='Lieu de naissance')),
                ('numero_de_telephone', models.CharField(blank=True, default='Numéro de téléphone non renseigné', max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('departement', models.CharField(blank=True, default='Département non renseigné', max_length=50, null=True, verbose_name='Département')),
                ('etablissement_d_origine', models.CharField(blank=True, default="Etablissement d'origine non renseigné", max_length=150, null=True, verbose_name="Etablissement d'origine")),
                ('annee_d_obtention_du_cepe', models.CharField(blank=True, default="Année d'obtention du CEPE non renseignée", max_length=4, null=True, verbose_name="Année d'obtention du CEPE")),
                ('copie_couleur_de_l_acte_de_naissance', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_actes_de_naissances/', verbose_name="Copie couleur de l'acte de naissance")),
                ('copie_couleur_d_une_piece_d_identite', models.FileField(blank=True, null=True, upload_to='copies_couleurs_des_pieces_d_identites/', verbose_name="Copie couleur de la pièce d'identité")),
                ('date_d_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Demande CEPE',
                'verbose_name_plural': 'Demandes CEPE',
                'ordering': ['-date_d_enregistrement'],
            },
        ),
    ]
