# Generated by Django 5.0.2 on 2024-05-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_bac',
            name='annee_d_obtention_du_bac',
            field=models.CharField(blank=True, default="Année d'obtention du BAC non renseignée", max_length=50, null=True, verbose_name="Année d'obtention du BAC"),
        ),
        migrations.AlterField(
            model_name='demande_bepc',
            name='annee_d_obtention_du_bepc',
            field=models.CharField(blank=True, default="Année d'obtention du BEPC non renseignée", max_length=50, null=True, verbose_name="Année d'obtention du BEPC"),
        ),
        migrations.AlterField(
            model_name='demande_cepe',
            name='annee_d_obtention_du_cepe',
            field=models.CharField(blank=True, default="Année d'obtention du CEPE non renseignée", max_length=50, null=True, verbose_name="Année d'obtention du CEPE"),
        ),
    ]
