# Generated by Django 5.0.2 on 2024-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0002_alter_demande_bac_annee_d_obtention_du_bac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_bac',
            name='date_de_naissance',
            field=models.CharField(blank=True, default='Date de naissance non renseignée', max_length=50, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='demande_bepc',
            name='date_de_naissance',
            field=models.CharField(blank=True, default='Date de naissance non renseignée', max_length=50, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='demande_cepe',
            name='date_de_naissance',
            field=models.CharField(blank=True, default='Date de naissance non renseignée', max_length=50, null=True, verbose_name='Date de naissance'),
        ),
    ]
