# Generated by Django 5.0.2 on 2024-05-07 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0004_alter_demande_bac_copie_couleur_d_une_piece_d_identite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activites_demande_bac',
            constraint=models.UniqueConstraint(fields=('demande', 'utilisateur', 'type_de_traitement'), name='contrainte_unique_activite_demande_bac'),
        ),
        migrations.AddConstraint(
            model_name='activites_demande_bepc',
            constraint=models.UniqueConstraint(fields=('demande', 'utilisateur', 'type_de_traitement'), name='contrainte_unique_activite_demande_bepc'),
        ),
        migrations.AddConstraint(
            model_name='activites_demande_cepe',
            constraint=models.UniqueConstraint(fields=('demande', 'utilisateur', 'type_de_traitement'), name='contrainte_unique_activite_demande_cepe'),
        ),
    ]
