# Generated by Django 5.0.2 on 2024-05-07 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Charge_De_Diplome',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent chargé de diplome")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent chargé de diplome")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_charges_de_diplomes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent chargé de diplome")),
                ('compte_agent_charge_de_diplome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent chargé de diplome',
                'verbose_name_plural': 'Agents chargés de diplomes',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Agent_De_Distribution',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent de distribution")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent de distribution")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_de_distributions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent de distribution")),
                ('compte_agent_de_distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent de distribution',
                'verbose_name_plural': 'Agents de distributions',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Agent_De_Production',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent de production")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent de production")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_de_productions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent de production")),
                ('compte_agent_de_production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent de production',
                'verbose_name_plural': 'Agents de productions',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Agent_De_Reception',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent de réception")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent de réception")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_de_receptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent de réception")),
                ('compte_agent_de_reception', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent de réception',
                'verbose_name_plural': 'Agents de réceptions',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Agent_De_Verification',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent de vérification")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent de vérification")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_de_verifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent de vérification")),
                ('compte_agent_de_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent de vérification',
                'verbose_name_plural': 'Agents de vérifications',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Agent_Regisseur',
            fields=[
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'agent régisseur")),
                ('prenoms', models.CharField(max_length=150, verbose_name="Prénom (s) de l'agent régisseur")),
                ('photo_de_profil', models.ImageField(upload_to='photos_de_profils_agents_regisseurs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name="Photo de profil de l'agent régisseur")),
                ('compte_agent_regisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Agent régisseur',
                'verbose_name_plural': 'Agents régisseurs',
                'ordering': ['-date_de_creation'],
            },
        ),
    ]
